Repository Ptome2000/ES-2024-25-2Sem-Sexta-LIGE-PL-A, pull requests merged in 2025-05, with the labels that each got.

#18 #geo 41
  src/main/java/DetectAdjacentProperties/AdjacencyDetector.java
  src/main/java/DetectAdjacentProperties/SpatialGrid.java
  src/main/java/Repository/CsvProcessor.java
  src/main/java/Repository/CsvValidator.java
  src/main/java/Services/GraphViewer.java
  src/main/java/Services/PropertyCollector.java
  src/main/java/Services/PropertyGraphJungBuilder.java
  src/main/java/Services/info.txt
  src/main/java/UserInterface/MainFrame.java
Labels: enhancement

#19 GEO-67 Merge CoordinateFinder Classes
  src/main/java/DetectAdjacentProperties/AdjacencyDetector.java
  src/main/java/DetectAdjacentProperties/CoordinateFinder.java
  src/main/java/DetectAdjacentProperties/MaxCoordinateFinder.java
  src/main/java/DetectAdjacentProperties/MinCoordinateFinder.java
  src/main/java/DetectAdjacentProperties/PropertyOwnership.java
  src/main/java/DetectAdjacentProperties/SpatialGrid.java
Labels: documentation, enhancement

#23 GEO-72 Tests for Models (without suggestions)
  src/main/java/Repository/CsvColum.java
  src/test/java/Models/DistrictTests.java
  src/test/java/Models/MunicipalityTests.java
  src/test/java/Models/ParishTests.java
  src/test/java/Models/PolygonTests.java
  src/test/java/Models/PropertyPolygonTests.java
  src/test/java/Models/VertexCoordinateTests.java
Labels: documentation, enhancement

#29 Avoid open Change Suggestions if is empty
  src/main/java/UserInterface/ChangeSuggestionsFrame.java
  src/main/java/UserInterface/MainFrame.java
Labels: bug

#30 GEO-88 - Spinner missing on when loading suggestions
  src/main/java/UserInterface/LoadingDialogSpinner.java
  src/main/java/UserInterface/MainFrame.java
Labels: bug

#33 GEO-70 Updated tests, fixed Cyclomatic Complexity and created custom annotations
  src/main/java/Annotations/CyclomaticComplexity.java
  src/main/java/Annotations/Layer.java
  src/main/java/Enums/LayerType.java
  src/main/java/Repository/CsvValidator.java
  src/main/java/Utils/MockedDistrict.java
  src/main/java/Utils/MockedMunicipality.java
  src/main/java/Utils/MockedParish.java
  src/test/java/Models/PropertyPolygonTests.java
  src/test/java/Models/VertexCoordinateTests.java
  src/test/java/Repository/CsvReaderTests.java
  src/test/java/Repository/CsvUploaderTests.java
  src/test/java/Repository/CsvValidatorTests.java
  src/test/java/Services/PropertyCollectorTests.java
  src/test/java/Services/PropertyGraphBuilderTests.java
Labels: documentation, enhancement

#35 GEO-77 - Calculate value similarity between two properties based on features
  src/main/java/ExchangeSuggestionEngine/SuggestionGenerator.java
  src/main/java/Models/ExchangeSuggestion.java
  src/main/java/Models/Municipality.java
  src/main/java/Models/Parish.java
  src/main/java/Models/PropertyPolygon.java
  src/main/java/Repository/CsvProcessor.java
  src/main/java/Services/PropertyScoreCalculator.java
  src/main/java/Services/SuggestionGenerator.java
  src/main/java/UserInterface/ChangeSuggestionsFrame.java
  src/main/java/UserInterface/MainFrame.java
Labels: enhancement

#36 GEO-76 -Integrate value similarity into exchange feasibility
  src/main/java/Models/ExchangeSuggestion.java
  src/main/java/Services/SuggestionGenerator.java
Labels: enhancement

#39 GEO-76 -Integrate value similarity into exchange feasibility
  src/main/java/UserInterface/ChangeSuggestionsFrame.java
Labels: enhancement

#40 Bug fix- Duplicated disctrict
  src/main/java/UserInterface/MainFrame.java
Labels: bug

#43 Bug fix #96 - Add Invalid CSV while running app in FrontEnd
  src/main/java/Repository/CsvValidator.java
Labels: bug

#44 GEO-86 Suggestion Tests, Updating and Documented and Grouped Tests
  pom.xml
  src/main/java/DetectAdjacentProperties/PropertyMerger.java
  src/main/java/DetectAdjacentProperties/SpatialGrid.java
  src/main/java/Repository/CsvColum.java
  src/main/java/Repository/CsvException.java
  src/main/java/Repository/CsvLogger.java
  src/main/java/Repository/CsvProcessor.java
  src/main/java/Repository/CsvReader.java
  src/main/java/Repository/CsvUploader.java
  src/main/java/Repository/CsvValidator.java
  src/main/java/Services/GraphViewer.java
  src/main/java/Services/PropertyCollector.java
  src/main/java/Services/PropertyGraphJungBuilder.java
  src/main/java/Services/PropertyInfoDialog.java
  src/main/java/Services/PropertyScoreCalculator.java
  src/main/java/Services/SuggestionGenerator.java
  src/main/java/UserInterface/ChangeSuggestionsFrame.java
  src/main/java/UserInterface/LoadingDialogSpinner.java
  src/main/java/UserInterface/MainFrame.java
  src/main/java/Utils/Annotations/CyclomaticComplexity.java
  src/main/java/Utils/Annotations/Layer.java
  src/main/java/Utils/Enums/LayerType.java
  src/main/java/Utils/Mocks/MockedPropertyPolygon.java
  src/test/java/DetectAdjacentProperties/AdjacencyDetectorTests.java
  src/test/java/DetectAdjacentProperties/AdjacentPropertyPairTests.java
  src/test/java/DetectAdjacentProperties/CoordinateFinderTests.java
  src/test/java/DetectAdjacentProperties/PropertyMergerTests.java
  src/test/java/DetectAdjacentProperties/PropertyOwnershipTests.java
  src/test/java/DetectAdjacentProperties/SpatialGridTests.java
  src/test/java/DetectAdjacentProperties/TestUtils.java
  src/test/java/Models/DistrictTests.java
  src/test/java/Models/ExchangeSuggestionTests.java
  src/test/java/Models/MunicipalityTests.java
  src/test/java/Models/ParishTests.java
  src/test/java/Models/PolygonTests.java
  src/test/java/Models/PropertyPolygonTests.java
  src/test/java/Models/VertexCoordinateTests.java
  src/test/java/Repository/CsvColumTests.java
  src/test/java/Repository/CsvExceptionTests.java
  src/test/java/Repository/CsvLoggerTests.java
  src/test/java/Repository/CsvProcessorTests.java
  src/test/java/Repository/CsvReaderTests.java
  src/test/java/Repository/CsvUploaderTests.java
  src/test/java/Repository/CsvValidatorTests.java
  src/test/java/Services/PropertyCollectorTests.java
  src/test/java/Services/PropertyGraphJungBuilderTests.java
  src/test/java/Services/PropertyScoreCalculatorTests.java
  src/test/java/Services/SuggestionGeneratorTests.java
  src/test/java/Services/TestUtils.java
Labels: documentation, enhancement

#55 GEO-28 Updated tests
  src/test/java/Repository/CsvProcessorTests.java
  src/test/java/Repository/CsvValidatorTests.java
Labels: documentation
